### ISSUE TITLE
FATAL: Command "git rev-parse /master^{commit}" returned status code 128:

### ISSUE THREAD

**Issue by hansode** [hansode/worklogs#27]
```
14:28:15  > git rev-parse /master^{commit} # timeout=10
14:28:15 FATAL: Command "git rev-parse /master^{commit}" returned status code 128:
14:28:15 stdout: /master^{commit}
14:28:15 
14:28:15 stderr: fatal: ambiguous argument '/master^{commit}': unknown revision or path not in the working tree.
14:28:15 Use '--' to separate paths from revisions
14:28:15 
14:28:15 hudson.plugins.git.GitException: Command "git rev-parse /master^{commit}" returned status code 128:
14:28:15 stdout: /master^{commit}
14:28:15 
14:28:15 stderr: fatal: ambiguous argument '/master^{commit}': unknown revision or path not in the working tree.
14:28:15 Use '--' to separate paths from revisions
14:28:15 
14:28:15    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1591)
14:28:15    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1567)
14:28:15    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1563)
14:28:15    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1249)
14:28:15    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1261)
14:28:15    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:622)
14:28:15    at hudson.plugins.git.GitAPI.revParse(GitAPI.java:316)
14:28:15    at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
14:28:15    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:28:15    at java.lang.reflect.Method.invoke(Method.java:616)
14:28:15    at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:299)
14:28:15    at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:280)
14:28:15    at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:239)
14:28:15    at hudson.remoting.UserRequest.perform(UserRequest.java:118)
14:28:15    at hudson.remoting.UserRequest.perform(UserRequest.java:48)
14:28:15    at hudson.remoting.Request$2.run(Request.java:326)
14:28:15    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
14:28:15    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
14:28:15    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
14:28:15    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
14:28:15    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
14:28:15    at java.lang.Thread.run(Thread.java:679)
14:28:15    at ......remote call to kemumaki12.ci02.dh(Native Method)
14:28:15    at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1356)
14:28:15    at hudson.remoting.UserResponse.retrieve(UserRequest.java:221)
14:28:15    at hudson.remoting.Channel.call(Channel.java:752)
14:28:15    at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:179)
14:28:15    at com.sun.proxy.$Proxy73.revParse(Unknown Source)
14:28:15    at org.jenkinsci.plugins.gitclient.RemoteGitImpl.revParse(RemoteGitImpl.java:546)
14:28:15    at hudson.plugins.git.extensions.impl.PreBuildMerge.decorateRevisionToBuild(PreBuildMerge.java:64)
14:28:15    at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:925)
14:28:15    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1017)
14:28:15    at hudson.scm.SCM.checkout(SCM.java:484)
14:28:15    at hudson.model.AbstractProject.checkout(AbstractProject.java:1270)
14:28:15    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:609)
14:28:15    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
14:28:15    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
14:28:15    at hudson.model.Run.execute(Run.java:1718)
14:28:15    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
14:28:15    at hudson.model.ResourceController.execute(ResourceController.java:89)
14:28:15    at hudson.model.Executor.run(Executor.java:240)
```

**Comment by hansode** [comment]
- [[#JENKINS-21845] Command "git rev-parse /develop^{commit}" returned status code 128 - Jenkins JIRA](https://issues.jenkins-ci.org/browse/JENKINS-21845)
- [[#JENKINS-21139] Git client fails to handle slashes in branch refs - Jenkins JIRA](https://issues.jenkins-ci.org/browse/JENKINS-21139)

**Comment by hansode** [comment]
- [GIT plugin](https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin): 2.3.5
  - https://github.com/jenkinsci/git-plugin
- [GIT client plugin](https://wiki.jenkins-ci.org/display/JENKINS/Git+Client+Plugin): 1.16.1
  - https://github.com/jenkinsci/git-client-plugin

**Comment by hansode** [comment]
![testing config jenkins](https://cloud.githubusercontent.com/assets/76867/6437707/5ff575ba-c105-11e4-92ea-2b27524259d3.png)

**Comment by hansode** [comment]
![testing config jenkins](https://cloud.githubusercontent.com/assets/76867/6437726/8bab4784-c105-11e4-8034-b6404c1b01a2.png)

**Comment by hansode** [comment]
Gitプラグインのバージョン組み合せ問題。
以前のバージョンに戻して解決。
