### ISSUE TITLE
Jenkins Git Pluginのバージョンによってtag付け成否が変化する

### ISSUE THREAD

**Issue by hansode** [hansode/worklogs#36]
```
19:03:58 Started by user anonymous
19:03:58 Building in workspace /var/lib/jenkins/jobs/foobar/workspace
19:03:58 Checkout:workspace / /var/lib/jenkins/jobs/foobar/workspace - hudson.remoting.LocalChannel@14e9925e
19:03:58 Using strategy: Default
19:03:58 Cloning the remote Git repository
19:03:58 Cloning repository https://github.com/hansode/git2rpm
19:03:58 git --version
19:03:58 git version 1.7.1
19:04:01 Fetching upstream changes from origin
19:04:03 Commencing build of Revision ed3e053f4ca00991a1684b9acc40a7416fdc6764 (origin/master)
19:04:03 Checking out Revision ed3e053f4ca00991a1684b9acc40a7416fdc6764 (origin/master)
19:04:03 FATAL: Could not apply tag jenkins-foobar-1
19:04:03 hudson.plugins.git.GitException: Could not apply tag jenkins-foobar-1
19:04:03    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.tag(CliGitAPIImpl.java:721)
19:04:03    at hudson.plugins.git.GitAPI.tag(GitAPI.java:211)
19:04:03    at hudson.plugins.git.GitSCM$4.invoke(GitSCM.java:1248)
19:04:03    at hudson.plugins.git.GitSCM$4.invoke(GitSCM.java:1205)
19:04:03    at hudson.FilePath.act(FilePath.java:989)
19:04:03    at hudson.FilePath.act(FilePath.java:967)
19:04:03    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1205)
19:04:03    at hudson.model.AbstractProject.checkout(AbstractProject.java:1270)
19:04:03    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:609)
19:04:03    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
19:04:03    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
19:04:03    at hudson.model.Run.execute(Run.java:1751)
19:04:03    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
19:04:03    at hudson.model.ResourceController.execute(ResourceController.java:89)
19:04:03    at hudson.model.Executor.run(Executor.java:240)
19:04:03 Caused by: hudson.plugins.git.GitException: Command "git tag -a -f -m Jenkins Build #1 jenkins-foobar-1" returned status code 128:
19:04:03 stdout: 
19:04:03 stderr: 
19:04:03 *** Please tell me who you are.
19:04:03 
19:04:03 Run
19:04:03 
19:04:03   git config --global user.email "you@example.com"
19:04:03   git config --global user.name "Your Name"
19:04:03 
19:04:03 to set your account's default identity.
19:04:03 Omit --global to set the identity only in this repository.
19:04:03 
19:04:03 fatal: empty ident  <jenkins@vagrant-centos6.(none)> not allowed
19:04:03 
19:04:03    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:790)
19:04:03    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:756)
19:04:03    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:766)
19:04:03    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.tag(CliGitAPIImpl.java:719)
19:04:03    ... 14 more
19:04:03 Finished: FAILURE
```

**Comment by hansode** [comment]
![foobar config jenkins](https://cloud.githubusercontent.com/assets/76867/6764633/80c2f02c-cffd-11e4-8f16-5727ae71fe45.png)

**Comment by hansode** [comment]
- 古いGitプラグイン: `Skip internal tag`を有効化する必要がある
- 最新Gitプラグイン: `Skip internal tag`有効無効が成否を左右しない
